{
 "title": "Custom API Exporter — Weather Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "query": {
     "query": "label_values(weather_temperature_celsius,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Response Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_api_response_time_seconds{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_visibility_meters{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_uv_index{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "weather_precipitation_mm{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloud Cover",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "weather_cloud_cover_percent{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feels Like Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_apparent_temperature_celsius{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "weather_windspeed_kmh{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "weather_humidity_percent{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius{city=\"$city\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}