{
 "title": "Postgre",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "query": {
     "query": "label_values(pg_database_size_bytes,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache hits rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"$database\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locks count by mode",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mode) (pg_locks_count{datname=\"$database\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit ratio %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_stat_database_blks_hit{datname=\"$database\"})\n/\n(pg_stat_database_blks_hit{datname=\"$database\"} + pg_stat_database_blks_read{datname=\"$database\"})\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Active Time (Total)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_active_time_seconds_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkpoint Write Time (Total)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time_total[60m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_roles_connection_limit{})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS (queries/tx per second, без pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"$database\"}[5m])\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"hospital_management\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read / Write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"$database\"}[5m])\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pg_stat_database_blks_written{datname=\"hospital_management\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$database\"} / 1024 / 1024  \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}