slice_name: Appointments by Specialization, Doctor, and Status
description: null
certified_by: null
certification_details: null
viz_type: sunburst_v2
params:
  datasource: 13__table
  viz_type: sunburst_v2
  columns:
  - level1
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: value
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(value)
    optionName: metric_iy1bh9n6nbd_i6ubyxrn4so
  adhoc_filters: []
  row_limit: 1000
  color_scheme: supersetColors
  show_labels: true
  show_labels_threshold: 5
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":13,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["level1"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"value","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(value)","optionName":"metric_iy1bh9n6nbd_i6ubyxrn4so"}],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"13__table","viz_type":"sunburst_v2","columns":["level1"],"metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"value","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(value)","optionName":"metric_iy1bh9n6nbd_i6ubyxrn4so"},"adhoc_filters":[],"row_limit":1000,"color_scheme":"supersetColors","show_labels":true,"show_labels_threshold":5,"label_type":"key","number_format":"SMART_NUMBER","date_format":"smart_date","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 7aa0bb79-6653-4c17-85c9-4caeaa601cb8
version: 1.0.0
dataset_uuid: 47ec104f-01b6-4229-b390-4833e7bff6a0
