slice_name: Appointments by Doctor Specialization and Status
description: null
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 12__table
  viz_type: heatmap_v2
  x_axis: specialization
  groupby: status
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(count)
    optionName: metric_pg7xgp2ogbl_lt5qyxrx4oa
  adhoc_filters: []
  row_limit: 1000
  normalize_across: heatmap
  legend_type: continuous
  linear_color_scheme: schemeYlGn
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  x_axis_time_format: smart_date
  show_legend: true
  show_percentage: true
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":12,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"specialization","label":"specialization","expressionType":"SQL"},"status"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"count","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(count)","optionName":"metric_pg7xgp2ogbl_lt5qyxrx4oa"}],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"rank","options":{"metric":"AVG(count)"}}]}],"form_data":{"datasource":"12__table","viz_type":"heatmap_v2","x_axis":"specialization","groupby":"status","metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"count","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(count)","optionName":"metric_pg7xgp2ogbl_lt5qyxrx4oa"},"adhoc_filters":[],"row_limit":1000,"normalize_across":"heatmap","legend_type":"continuous","linear_color_scheme":"schemeYlGn","xscale_interval":-1,"yscale_interval":-1,"left_margin":"auto","bottom_margin":"auto","value_bounds":[null,null],"y_axis_format":"SMART_NUMBER","x_axis_time_format":"smart_date","show_legend":true,"show_percentage":true,"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: cfb35711-60ce-4b13-a6fd-e751211f3e6e
version: 1.0.0
dataset_uuid: e57b7f7a-f4ec-4050-bc0a-5461588b6533
