slice_name: Doctor Experience vs Patient Load
description: null
certified_by: null
certification_details: null
viz_type: bubble_v2
params:
  datasource: 10__table
  viz_type: bubble_v2
  entity: doctor_id
  x:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: years_experience
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(years_experience)
    optionName: metric_0euemr6hg5r_zgmi05khy3e
  y:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_appointments
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(total_appointments)
    optionName: metric_dhkvf63l9to_0hhk9zj64mz
  adhoc_filters: []
  size:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: unique_patients
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(unique_patients)
    optionName: metric_oazv2mmtjle_4lcief5cris
  order_desc: true
  row_limit: 1000
  color_scheme: supersetColors
  show_legend: true
  legendType: scroll
  legendOrientation: top
  legendMargin: null
  max_bubble_size: '25'
  tooltipSizeFormat: SMART_NUMBER
  opacity: 0.6
  x_axis_label: Years of Experience
  x_axis_title_margin: 30
  xAxisFormat: SMART_NUMBER
  y_axis_label: Total Appointments
  y_axis_title_margin: 30
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":10,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["doctor_id"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"years_experience","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(years_experience)","optionName":"metric_0euemr6hg5r_zgmi05khy3e"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_appointments","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(total_appointments)","optionName":"metric_dhkvf63l9to_0hhk9zj64mz"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"unique_patients","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(unique_patients)","optionName":"metric_oazv2mmtjle_4lcief5cris"}],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"10__table","viz_type":"bubble_v2","entity":"doctor_id","x":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"years_experience","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(years_experience)","optionName":"metric_0euemr6hg5r_zgmi05khy3e"},"y":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_appointments","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(total_appointments)","optionName":"metric_dhkvf63l9to_0hhk9zj64mz"},"adhoc_filters":[],"size":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"unique_patients","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(unique_patients)","optionName":"metric_oazv2mmtjle_4lcief5cris"},"order_desc":true,"row_limit":1000,"color_scheme":"supersetColors","show_legend":true,"legendType":"scroll","legendOrientation":"top","legendMargin":null,"max_bubble_size":"25","tooltipSizeFormat":"SMART_NUMBER","opacity":0.6,"x_axis_label":"Years
  of Experience","x_axis_title_margin":30,"xAxisFormat":"SMART_NUMBER","y_axis_label":"Total
  Appointments","y_axis_title_margin":30,"y_axis_format":"SMART_NUMBER","truncateXAxis":true,"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: bb3d96ec-ea2c-48d4-9d03-065f52b65b05
version: 1.0.0
dataset_uuid: 063099bd-f6fc-4dea-b8bc-666f0870f226
