slice_name: Most Common Treatment Types
description: null
certified_by: null
certification_details: null
viz_type: word_cloud
params:
  datasource: 15__table
  viz_type: word_cloud
  series: word
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: frequency
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(frequency)
    optionName: metric_o1uyoqtlsp_h0mo01wiyw
  adhoc_filters: []
  row_limit: 1000
  size_from: 10
  size_to: 70
  rotation: square
  color_scheme: supersetColors
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":15,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["word"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"frequency","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(frequency)","optionName":"metric_o1uyoqtlsp_h0mo01wiyw"}],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"15__table","viz_type":"word_cloud","series":"word","metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"frequency","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(frequency)","optionName":"metric_o1uyoqtlsp_h0mo01wiyw"},"adhoc_filters":[],"row_limit":1000,"size_from":10,"size_to":70,"rotation":"square","color_scheme":"supersetColors","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 524cf916-7b56-471d-8d2b-22f1295bdfca
version: 1.0.0
dataset_uuid: 7b43dcd0-bb35-4b22-98ed-fd2081294a87
